es:
  only:
    - master
language: node_js
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
node_js:
  - stable

script:
  - cd jekyll-blog
  - git clone --depth=1 --branch=master https://github.com/HOHOOO/HOHOOO.github.io.git _posts
  - bundle install
  - jekyll build
  - cat ./public/css/base.css # just for verify changes
  - ../qshell_linux_amd64 qupload scripts/qiniu.conf.json
after_success:
  - |
    cd _site
    touch .nojekyll
    git init
    git add .
    git commit -m "Deploy at `date +"%Y-%m-%d %H:%M"`"
    # Make sure to make the output quiet, or else the API token will leak!
    git push -f -q https://github.com/HOHOOO/HOHOOO.github.io.git master:master > /dev/null 2>&1
