permalink: /:year-:month-:day-:title/
paginate: 10
markdown: kramdown
encoding: utf-8

# 作者信息
author: 
  name: 吕立青
  email: lv460051518@gmail.com
  link: https://blog.jimmylv.info
  weibo: https://weibo.com/liqing215
  github: https://github.com/JimmyLv
  zhihu: https://www.zhihu.com/people/JimmyLv

# 站点信息
title: 吕立青的博客
url: https://blog.jimmylv.info
repo: https://github.com/JimmyLv/jimmylv.github.io

exclude:
  - _wiki/
  - .github/
  - .travis/
